version: '3.9'

services:
  iris:
    container_name: iris
    image: containers.intersystems.com/intersystems/iris:2023.1.1.380.0
    hostname: iris
    ports:
    - 1972:1972
    - 2188:2188
    - 52773:52773
    - 53773:53773
    volumes:
    - ./iris.key:/isc-mirror/iris.key
    command: --key /isc-mirror/iris.key
